### ISSUE TITLE
CANFDuino-master.zip-Archive corrupted

### ISSUE THREAD

**Issue by Dzintars76** [togglebit/CANFDuino#1]
Hi,

Tried un-zip CANFDuino-master.zip but received error message: Archive corrupted

Any idea? Thank you in advance for help

**Comment by togglebit** [comment]
Okay I will look into it and get back to you

**Comment by togglebit** [comment]
Just tried this, works on my machine. Are you sure the whole zip file downloaded? Unzipped should be about 58MB.
![image](https://user-images.githubusercontent.com/4099763/145660666-f5e77bef-11e5-475f-a8fa-aeee9f01a1f9.png)
![Image](https://user-images.githubusercontent.com/4099763/145660676-d468d065-d59b-4edb-935f-6dbe25730e7b.png)

**Comment by Dzintars76** [comment]
Hi,

Thanks for reply.  Unzipped 58.4 MB.
I've tried on two different computers and same result.
![20211211_160100](https://user-images.githubusercontent.com/95937965/145679461-55158a33-040b-41d1-bdee-bba8a5ce716e.jpg)
![16392315144945257917587895404488](https://user-images.githubusercontent.com/95937965/145679476-59a2eaad-2fb6-46b1-83b9-6a878f6c2966.jpg)

**Comment by Dzintars76** [comment]
Both computers windows 10

**Comment by togglebit** [comment]
Ok I think its possible the IDE is getting confused by the zip file. It
actually needs to be the unzipped folder "CANFDuino" placed in the hardware
folder. Here is another set of instructions with pictures:
https://togglebit.net/getting-started-with-canfduino/

**Comment by Dzintars76** [comment]
Thanks for help, finally sorted out.
