### ISSUE TITLE
Wrong flash and SRAM sizes for CANFDuino17A

### ISSUE THREAD

**Issue by maxgerhardt** [togglebit/CANFDuino#3]
[Atmel says](https://www.microchip.com/en-us/product/ATSAMC21G17A)

![grafik](https://user-images.githubusercontent.com/26485477/219167961-162cd62a-b273-48a0-800e-4aeb4af236c1.png)

Your board.txt says

https://github.com/togglebit/CANFDuino/blob/3f4ddddb9db5f7833d39deceb101c792b12c27b2/samd/boards.txt#L74

so that doesn't match. Also you don't even seem to be specifying maximum_ram_size for either boards.

**Comment by togglebit** [comment]
TY Will fix
