### ISSUE TITLE
can i use interrupts in arduino ide ? 

### ISSUE THREAD

**Issue by ehd2001** [togglebit/CANFDuino#6]
can i use interrupts in arduino ide ? or i need to use register bits 
im trying to count freq less 1khz

**Comment by togglebit** [comment]
yes you can use interrupts, for external interrupts see the arduino
reference https://www.arduino.cc/en/Reference/attachInterrupt . If you are
looking for a timer specific to the samc21, then I can upload some examples

**Comment by ehd2001** [comment]
Can you please upload some example and what pins are the interrupt ?

**Comment by togglebit** [comment]
Just updated the readme and examples for you, sorry for the delay.
## Interrupts 
***CANFDuino_TimerTx.ino CANFDuino_Interrupt.ino***

These are the simple test sketches for using a SAMC21 timer as a periodic callback for sending CAN messages (or doing other things) as well as a very simple bare-bones example of a digital input implemented as an external interrupt (note variant.cpp maps the external interrupts themselves to "Arduino" pins which must be referenced against the SAMC21 datasheet for pin mapping).
